#!/usr/bin/env node
// ══════════════════════════════════════════════════════════════
//  SmartTransfer — Automatic Setup Script
//  Usage: node setup.js
//
//  This script reads setup.config.json and automatically:
//  1. Generates all .env files (backend + frontend)
//  2. Updates mobile app config files (driver-app + partner-app)
//  3. Installs npm dependencies
//  4. Runs Prisma migrations
//  5. Builds frontend
//  6. Generates PM2 ecosystem file
//  7. Generates Nginx config
//  8. Optionally sets up SSL with certbot
// ══════════════════════════════════════════════════════════════

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const crypto = require('crypto');
const readline = require('readline');

const ROOT = __dirname;
const CONFIG_FILE = path.join(ROOT, 'setup.config.json');

// ── Colors for terminal output ──
const c = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  dim: '\x1b[2m',
};

function log(msg) { console.log(`${c.green}✓${c.reset} ${msg}`); }
function warn(msg) { console.log(`${c.yellow}⚠${c.reset} ${msg}`); }
function err(msg) { console.log(`${c.red}✗${c.reset} ${msg}`); }
function info(msg) { console.log(`${c.cyan}ℹ${c.reset} ${msg}`); }
function header(msg) { console.log(`\n${c.bright}${c.blue}═══ ${msg} ═══${c.reset}\n`); }

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => rl.question(`${c.cyan}?${c.reset} ${question} `, ans => { rl.close(); resolve(ans.trim()); }));
}

// ── Load or create config ──
function loadConfig() {
  if (!fs.existsSync(CONFIG_FILE)) {
    err('setup.config.json bulunamadı!');
    info('Lütfen önce setup.config.json dosyasını oluşturun.');
    process.exit(1);
  }

  const raw = fs.readFileSync(CONFIG_FILE, 'utf8');
  // Strip comment keys (keys starting with "//")
  const config = JSON.parse(raw);
  for (const key of Object.keys(config)) {
    if (key.startsWith('//')) delete config[key];
  }
  return config;
}

// ── Generate random JWT secret if empty ──
function ensureJwtSecret(config) {
  if (!config.security.jwtSecret) {
    config.security.jwtSecret = crypto.randomBytes(32).toString('hex');
    info(`JWT Secret otomatik oluşturuldu: ${config.security.jwtSecret.substring(0, 16)}...`);
  }
}

// ══════════════════════════════════════════════════════════════
//  STEP 1: Generate Backend .env
// ══════════════════════════════════════════════════════════════
function generateBackendEnv(config) {
  const protocol = config.ssl?.enabled ? 'https' : 'http';
  const backendUrl = `${protocol}://${config.domain.backend}`;
  const frontendUrl = `${protocol}://${config.domain.frontend}`;

  const env = `# ══════════════════════════════════════════════════════════════
# SmartTransfer Backend — Auto-generated by setup.js
# Generated: ${new Date().toISOString()}
# ══════════════════════════════════════════════════════════════

# PostgreSQL
DATABASE_URL="${config.database.url}"

# JWT
JWT_SECRET=${config.security.jwtSecret}
JWT_EXPIRATION=${config.security.jwtExpiration || '7d'}
REFRESH_TOKEN_EXPIRATION=${config.security.refreshTokenExpiration || '7d'}

# Server
PORT=${config.server.backendPort || 4000}
NODE_ENV=${config.server.nodeEnv || 'production'}

# Public URLs
BACKEND_URL=${backendUrl}
FRONTEND_URL=${frontendUrl}

# API Keys
AVIATIONSTACK_API_KEY=${config.apiKeys?.aviationstackApiKey || ''}

# Integrations
N8N_WEBHOOK_URL=${config.integrations?.n8nWebhookUrl || ''}
`;

  const envPath = path.join(ROOT, 'backend', '.env');
  fs.writeFileSync(envPath, env, 'utf8');
  log(`Backend .env oluşturuldu: ${envPath}`);

  // Also create .env.production
  fs.writeFileSync(path.join(ROOT, 'backend', '.env.production'), env, 'utf8');
}

// ══════════════════════════════════════════════════════════════
//  STEP 2: Generate Frontend .env.production
// ══════════════════════════════════════════════════════════════
function generateFrontendEnv(config) {
  const protocol = config.ssl?.enabled ? 'https' : 'http';
  const backendUrl = `${protocol}://${config.domain.backend}`;

  const envProd = `# ══════════════════════════════════════════════════════════════
# SmartTransfer Frontend — Auto-generated by setup.js
# Generated: ${new Date().toISOString()}
# ══════════════════════════════════════════════════════════════

NEXT_PUBLIC_API_URL=${backendUrl}
NEXT_PUBLIC_SOCKET_URL=${backendUrl}
NEXT_PUBLIC_TENANT_SLUG=${config.company.tenantSlug || 'smarttravel-demo'}
NEXT_PUBLIC_HERE_API_KEY=${config.apiKeys?.hereApiKey || ''}
`;

  const envLocal = `# Development — localhost
NEXT_PUBLIC_API_URL=http://localhost:${config.server.backendPort || 4000}
NEXT_PUBLIC_SOCKET_URL=http://localhost:${config.server.backendPort || 4000}
NEXT_PUBLIC_TENANT_SLUG=${config.company.tenantSlug || 'smarttravel-demo'}
NEXT_PUBLIC_HERE_API_KEY=${config.apiKeys?.hereApiKey || ''}
`;

  fs.writeFileSync(path.join(ROOT, 'frontend', '.env.production'), envProd, 'utf8');
  fs.writeFileSync(path.join(ROOT, 'frontend', '.env.local'), envLocal, 'utf8');
  log('Frontend .env.production oluşturuldu');
  log('Frontend .env.local oluşturuldu');
}

// ══════════════════════════════════════════════════════════════
//  STEP 3: Update Mobile App Configs
// ══════════════════════════════════════════════════════════════
function generateMobileConfigs(config) {
  const protocol = config.ssl?.enabled ? 'https' : 'http';
  const backendUrl = `${protocol}://${config.domain.backend}`;
  const tenant = config.company.tenantSlug || 'smarttravel-demo';

  const configContent = `// ── SmartTransfer — Auto-generated by setup.js ──
// Generated: ${new Date().toISOString()}
// DO NOT edit manually. Run 'node setup.js' to regenerate.

export const API_URL = '${backendUrl}/api';
export const SOCKET_URL = '${backendUrl}';
export const TENANT_SLUG = '${tenant}';
export const BASE_URL = API_URL.replace(/\\/api$/, '');
`;

  // Driver App
  const driverConfigPath = path.join(ROOT, 'driver-app', 'config.ts');
  fs.writeFileSync(driverConfigPath, configContent, 'utf8');
  log('Driver App config.ts güncellendi');

  // Partner App
  const partnerConfigPath = path.join(ROOT, 'partner-app', 'config.ts');
  fs.writeFileSync(partnerConfigPath, configContent, 'utf8');
  log('Partner App config.ts güncellendi');

  // Also update hardcoded URLs in driver-app/index.js (headless background tasks)
  const indexJsPath = path.join(ROOT, 'driver-app', 'index.js');
  if (fs.existsSync(indexJsPath)) {
    let content = fs.readFileSync(indexJsPath, 'utf8');
    // Replace any API_URL definition at the top
    content = content.replace(
      /const API_URL = ['"].*?['"]/,
      `const API_URL = '${backendUrl}/api'`
    );
    // Replace tenant slug in fetch headers
    content = content.replace(
      /'X-Tenant-Slug':\s*'[^']*'/g,
      `'X-Tenant-Slug': '${tenant}'`
    );
    fs.writeFileSync(indexJsPath, content, 'utf8');
    log('Driver App index.js (headless) güncellendi');
  }

  // Update driver-app context files
  const driverFiles = [
    'context/AuthContext.tsx',
    'context/SocketContext.tsx',
    'app/_layout.tsx',
    'app/index.tsx',
    'app/ratings.tsx',
    'app/messages.tsx',
    'app/history.tsx',
    'app/job/[id].tsx',
    'app/job/shuttle-map.tsx',
    'app/(tabs)/index.tsx',
    'app/(tabs)/profile.tsx',
    'app/(tabs)/fuel.tsx',
    'app/(tabs)/explore.tsx',
    'app/(tabs)/accounting.tsx',
  ];

  let driverCount = 0;
  for (const relPath of driverFiles) {
    const filePath = path.join(ROOT, 'driver-app', relPath);
    if (!fs.existsSync(filePath)) continue;
    let content = fs.readFileSync(filePath, 'utf8');

    // Replace API_URL constant declarations
    const oldContent = content;
    content = content.replace(
      /const (API_URL|SOCKET_URL)\s*=\s*['"]https?:\/\/[^'"]+['"]/g,
      (match, varName) => {
        if (varName === 'SOCKET_URL') return `const SOCKET_URL = '${backendUrl}'`;
        return `const API_URL = '${backendUrl}/api'`;
      }
    );
    // Replace tenant slug
    content = content.replace(
      /'X-Tenant-Slug':\s*'[^']*'/g,
      `'X-Tenant-Slug': '${tenant}'`
    );

    if (content !== oldContent) {
      fs.writeFileSync(filePath, content, 'utf8');
      driverCount++;
    }
  }
  if (driverCount > 0) {
    log(`Driver App: ${driverCount} dosya güncellendi`);
  }
}

// ══════════════════════════════════════════════════════════════
//  STEP 4: Generate PM2 Ecosystem File
// ══════════════════════════════════════════════════════════════
function generatePM2Config(config) {
  const ecosystem = {
    apps: [
      {
        name: 'smarttransfer-backend',
        cwd: './backend',
        script: 'index.js',
        env: {
          NODE_ENV: config.server.nodeEnv || 'production',
          PORT: config.server.backendPort || 4000,
        },
        instances: 1,
        exec_mode: 'fork',
        watch: false,
        max_memory_restart: '500M',
        error_file: './logs/backend-error.log',
        out_file: './logs/backend-out.log',
        log_date_format: 'YYYY-MM-DD HH:mm:ss',
      },
      {
        name: 'smarttransfer-frontend',
        cwd: './frontend',
        script: 'node_modules/.bin/next',
        args: 'start -p ' + (config.server.frontendPort || 3000),
        env: {
          NODE_ENV: 'production',
        },
        instances: 1,
        exec_mode: 'fork',
        watch: false,
        max_memory_restart: '500M',
        error_file: './logs/frontend-error.log',
        out_file: './logs/frontend-out.log',
        log_date_format: 'YYYY-MM-DD HH:mm:ss',
      }
    ]
  };

  const pm2Path = path.join(ROOT, 'ecosystem.config.js');
  fs.writeFileSync(pm2Path, `module.exports = ${JSON.stringify(ecosystem, null, 2)};\n`, 'utf8');
  log('PM2 ecosystem.config.js oluşturuldu');

  // Create logs directory
  const logsDir = path.join(ROOT, 'logs');
  if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });
}

// ══════════════════════════════════════════════════════════════
//  STEP 5: Generate Nginx Config
// ══════════════════════════════════════════════════════════════
function generateNginxConfig(config) {
  const backendPort = config.server.backendPort || 4000;
  const frontendPort = config.server.frontendPort || 3000;

  const nginx = `# ══════════════════════════════════════════════════════════════
# SmartTransfer — Nginx Config (Auto-generated by setup.js)
# Copy this to /etc/nginx/sites-available/smarttransfer
# Then: sudo ln -s /etc/nginx/sites-available/smarttransfer /etc/nginx/sites-enabled/
# Then: sudo nginx -t && sudo systemctl reload nginx
# Then: sudo certbot --nginx -d ${config.domain.frontend} -d ${config.domain.backend}
# ══════════════════════════════════════════════════════════════

# Frontend
server {
    listen 80;
    server_name ${config.domain.frontend} www.${config.domain.frontend};

    location / {
        proxy_pass http://127.0.0.1:${frontendPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

# Backend API + WebSocket
server {
    listen 80;
    server_name ${config.domain.backend};

    client_max_body_size 50M;

    # API routes
    location / {
        proxy_pass http://127.0.0.1:${backendPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Socket.IO WebSocket
    location /socket.io/ {
        proxy_pass http://127.0.0.1:${backendPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    # Raw WebSocket for driver native app
    location /ws/ {
        proxy_pass http://127.0.0.1:${backendPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    # Static uploads
    location /uploads/ {
        proxy_pass http://127.0.0.1:${backendPort}/uploads/;
        proxy_cache_valid 200 7d;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
`;

  const nginxPath = path.join(ROOT, 'nginx.conf');
  fs.writeFileSync(nginxPath, nginx, 'utf8');
  log(`Nginx config oluşturuldu: ${nginxPath}`);
  info('Kopyalayın: sudo cp nginx.conf /etc/nginx/sites-available/smarttransfer');
}

// ══════════════════════════════════════════════════════════════
//  STEP 6: Install Dependencies
// ══════════════════════════════════════════════════════════════
function installDeps(dir, name) {
  const fullPath = path.join(ROOT, dir);
  if (!fs.existsSync(path.join(fullPath, 'package.json'))) {
    warn(`${name}: package.json bulunamadı, atlanıyor`);
    return;
  }
  info(`${name}: npm install çalıştırılıyor...`);
  try {
    execSync('npm install --production', { cwd: fullPath, stdio: 'pipe' });
    log(`${name}: Bağımlılıklar yüklendi`);
  } catch (e) {
    err(`${name}: npm install başarısız — ${e.message}`);
  }
}

// ══════════════════════════════════════════════════════════════
//  STEP 7: Prisma Setup
// ══════════════════════════════════════════════════════════════
function runPrisma() {
  const backendPath = path.join(ROOT, 'backend');
  info('Prisma client üretiliyor...');
  try {
    execSync('npx prisma generate', { cwd: backendPath, stdio: 'pipe' });
    log('Prisma client üretildi');
  } catch (e) {
    err(`Prisma generate başarısız: ${e.message}`);
    return;
  }

  info('Veritabanı şeması senkronize ediliyor...');
  try {
    execSync('npx prisma db push', { cwd: backendPath, stdio: 'pipe' });
    log('Veritabanı şeması senkronize edildi');
  } catch (e) {
    err(`Prisma db push başarısız: ${e.message}`);
  }
}

// ══════════════════════════════════════════════════════════════
//  STEP 7b: Seed Database
// ══════════════════════════════════════════════════════════════
function seedDatabase() {
  const backendPath = path.join(ROOT, 'backend');
  info('Veritabanı demo verileri yükleniyor...');
  try {
    execSync('node prisma/seed.js', { cwd: backendPath, stdio: 'pipe' });
    log('Veritabanı seed tamamlandı (Tenant, Roller, Kullanıcılar)');
  } catch (e) {
    // Seed may fail if data already exists (upsert), that's OK
    if (e.message && e.message.includes('Unique constraint')) {
      warn('Seed: Veriler zaten mevcut, atlanıyor');
    } else {
      err(`Seed başarısız: ${e.stderr ? e.stderr.toString().substring(0, 200) : e.message}`);
    }
  }
}

// ══════════════════════════════════════════════════════════════
//  STEP 8: Build Frontend
// ══════════════════════════════════════════════════════════════
function buildFrontend() {
  const frontendPath = path.join(ROOT, 'frontend');
  info('Frontend build ediliyor (bu birkaç dakika sürebilir)...');
  try {
    execSync('npm run build', { cwd: frontendPath, stdio: 'pipe', timeout: 300000 });
    log('Frontend build tamamlandı');
  } catch (e) {
    err(`Frontend build başarısız: ${e.message}`);
  }
}

// ══════════════════════════════════════════════════════════════
//  MAIN
// ══════════════════════════════════════════════════════════════
async function main() {
  console.log(`
${c.bright}${c.cyan}╔══════════════════════════════════════════════════╗
║                                                  ║
║     🚀  SmartTransfer Setup Wizard               ║
║         Otomatik Kurulum Sihirbazı               ║
║                                                  ║
╚══════════════════════════════════════════════════╝${c.reset}
`);

  // Load config
  const config = loadConfig();

  // Validate required fields
  const errors = [];
  if (!config.domain?.frontend) errors.push('domain.frontend boş');
  if (!config.domain?.backend) errors.push('domain.backend boş');
  if (!config.database?.url || config.database.url.includes('user:password')) errors.push('database.url ayarlanmamış');

  if (errors.length > 0) {
    err('setup.config.json dosyasında eksik alanlar var:');
    errors.forEach(e => console.log(`   ${c.red}•${c.reset} ${e}`));
    console.log(`\n   Lütfen ${c.cyan}setup.config.json${c.reset} dosyasını düzenleyin ve tekrar çalıştırın.\n`);
    process.exit(1);
  }

  // Show config summary
  header('Yapılandırma Özeti');
  console.log(`   Şirket:     ${c.bright}${config.company?.name || 'SmartTransfer'}${c.reset}`);
  console.log(`   Tenant:     ${config.company?.tenantSlug || 'smarttravel-demo'}`);
  console.log(`   Frontend:   ${c.cyan}${config.domain.frontend}${c.reset}`);
  console.log(`   Backend:    ${c.cyan}${config.domain.backend}${c.reset}`);
  console.log(`   Database:   ${config.database.url.substring(0, 40)}...`);
  console.log(`   SSL:        ${config.ssl?.enabled ? `${c.green}Evet${c.reset}` : `${c.yellow}Hayır${c.reset}`}`);
  console.log('');

  const confirm = await ask('Bu ayarlarla kuruluma devam edilsin mi? (E/h)');
  if (confirm.toLowerCase() === 'h' || confirm.toLowerCase() === 'n') {
    info('Kurulum iptal edildi.');
    process.exit(0);
  }

  ensureJwtSecret(config);

  // Save back config with generated secret
  const configToSave = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
  for (const key of Object.keys(configToSave)) {
    if (key.startsWith('//')) delete configToSave[key];
  }
  configToSave.security = configToSave.security || {};
  configToSave.security.jwtSecret = config.security.jwtSecret;
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(configToSave, null, 2), 'utf8');

  // ── Run all steps ──
  header('Adım 1/8: Konfigürasyon Dosyaları');
  generateBackendEnv(config);
  generateFrontendEnv(config);
  generateMobileConfigs(config);

  header('Adım 2/8: PM2 Ecosystem');
  generatePM2Config(config);

  header('Adım 3/8: Nginx Config');
  generateNginxConfig(config);

  header('Adım 4/8: Backend Bağımlılıkları');
  installDeps('backend', 'Backend');

  header('Adım 5/8: Prisma Veritabanı');
  runPrisma();

  header('Adım 6/8: Veritabanı Demo Verileri');
  seedDatabase();

  header('Adım 7/8: Frontend Bağımlılıkları');
  installDeps('frontend', 'Frontend');

  header('Adım 8/8: Frontend Build');
  buildFrontend();

  // ── Final Summary ──
  const protocol = config.ssl?.enabled ? 'https' : 'http';
  console.log(`
${c.bright}${c.green}╔══════════════════════════════════════════════════╗
║                                                  ║
║     ✅  Kurulum Tamamlandı!                      ║
║                                                  ║
╚══════════════════════════════════════════════════╝${c.reset}

${c.bright}Sonraki Adımlar:${c.reset}

  ${c.cyan}1.${c.reset} Nginx config'i kopyalayın:
     ${c.dim}sudo cp nginx.conf /etc/nginx/sites-available/smarttransfer${c.reset}
     ${c.dim}sudo ln -s /etc/nginx/sites-available/smarttransfer /etc/nginx/sites-enabled/${c.reset}
     ${c.dim}sudo nginx -t && sudo systemctl reload nginx${c.reset}

  ${c.cyan}2.${c.reset} SSL sertifikası kurun:
     ${c.dim}sudo certbot --nginx -d ${config.domain.frontend} -d ${config.domain.backend}${c.reset}

  ${c.cyan}3.${c.reset} PM2 ile başlatın:
     ${c.dim}pm2 start ecosystem.config.js${c.reset}
     ${c.dim}pm2 save${c.reset}
     ${c.dim}pm2 startup${c.reset}

  ${c.cyan}4.${c.reset} Test edin:
     ${c.dim}${protocol}://${config.domain.backend}/health${c.reset}
     ${c.dim}${protocol}://${config.domain.frontend}${c.reset}

  ${c.cyan}5.${c.reset} Mobil APK build (opsiyonel):
     ${c.dim}cd driver-app && npx expo run:android --variant release${c.reset}

${c.bright}Oluşturulan Dosyalar:${c.reset}
  • backend/.env
  • frontend/.env.production
  • frontend/.env.local
  • driver-app/config.ts
  • partner-app/config.ts
  • ecosystem.config.js  ${c.dim}(PM2)${c.reset}
  • nginx.conf            ${c.dim}(Nginx)${c.reset}
`);
}

main().catch(e => {
  err(`Kurulum hatası: ${e.message}`);
  process.exit(1);
});
