const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CONFIG_FILE = path.join(ROOT, 'setup.config.json');

function loadConfig() {
  const raw = fs.readFileSync(CONFIG_FILE, 'utf8');
  const config = JSON.parse(raw);
  for (const key of Object.keys(config)) {
    if (key.startsWith('//')) delete config[key];
  }
  return config;
}

function generateMobileConfigs(config) {
  const protocol = config.ssl?.enabled ? 'https' : 'http';
  const backendUrl = `${protocol}://${config.domain.backend}`;
  const tenant = config.company.tenantSlug || 'smarttravel-demo';

  console.log(`Updating mobile apps to use backend: ${backendUrl}`);

  const configContent = `// ── SmartTransfer — Auto-generated by setup.js ──
// Generated: ${new Date().toISOString()}
// DO NOT edit manually. Run 'node setup.js' to regenerate.

export const API_URL = '${backendUrl}/api';
export const SOCKET_URL = '${backendUrl}';
export const TENANT_SLUG = '${tenant}';
export const BASE_URL = API_URL.replace(/\\/api$/, '');
`;

  // Driver App
  const driverConfigPath = path.join(ROOT, 'driver-app', 'config.ts');
  fs.writeFileSync(driverConfigPath, configContent, 'utf8');
  console.log('Driver App config.ts updated');

  // Partner App
  const partnerConfigPath = path.join(ROOT, 'partner-app', 'config.ts');
  fs.writeFileSync(partnerConfigPath, configContent, 'utf8');
  console.log('Partner App config.ts updated');

  // Driver App headless
  const indexJsPath = path.join(ROOT, 'driver-app', 'index.js');
  if (fs.existsSync(indexJsPath)) {
    let content = fs.readFileSync(indexJsPath, 'utf8');
    content = content.replace(
      /const API_URL = ['"].*?['"]/,
      `const API_URL = '${backendUrl}/api'`
    );
    content = content.replace(
      /'X-Tenant-Slug':\s*'[^']*'/g,
      `'X-Tenant-Slug': '${tenant}'`
    );
    fs.writeFileSync(indexJsPath, content, 'utf8');
  }

  // Update driver-app context files
  const driverFiles = [
    'context/AuthContext.tsx',
    'context/SocketContext.tsx',
    'app/_layout.tsx',
    'app/index.tsx',
    'app/ratings.tsx',
    'app/messages.tsx',
    'app/history.tsx',
    'app/job/[id].tsx',
    'app/job/shuttle-map.tsx',
    'app/(tabs)/index.tsx',
    'app/(tabs)/profile.tsx',
    'app/(tabs)/fuel.tsx',
    'app/(tabs)/explore.tsx',
    'app/(tabs)/accounting.tsx',
  ];

  let driverCount = 0;
  for (const relPath of driverFiles) {
    const filePath = path.join(ROOT, 'driver-app', relPath);
    if (!fs.existsSync(filePath)) continue;
    let content = fs.readFileSync(filePath, 'utf8');

    const oldContent = content;
    content = content.replace(
      /const (API_URL|SOCKET_URL)\s*=\s*['"]https?:\/\/[^'"]+['"]/g,
      (match, varName) => {
        if (varName === 'SOCKET_URL') return `const SOCKET_URL = '${backendUrl}'`;
        return `const API_URL = '${backendUrl}/api'`;
      }
    );
    content = content.replace(
      /'X-Tenant-Slug':\s*'[^']*'/g,
      `'X-Tenant-Slug': '${tenant}'`
    );

    if (content !== oldContent) {
      fs.writeFileSync(filePath, content, 'utf8');
      driverCount++;
    }
  }
  console.log(`Driver App: ${driverCount} file(s) updated`);
}

const config = loadConfig();
generateMobileConfigs(config);
