// ── SmartTransfer — Auto-generated by setup.js ──
// Generated: 2026-05-16T22:34:32.644Z
// DO NOT edit manually. Run 'node setup.js' to regenerate.

export const API_URL = 'https://api.jet2home.com/api';
export const SOCKET_URL = 'https://api.jet2home.com';
export const TENANT_SLUG = 'Jet2Home';
export const BASE_URL = API_URL.replace(/\/api$/, '');
